### PR TITLE
#165663486 Create database models

### PR DESCRIPTION
**Pull request by rwajon**
#### What does this PR do?
Create database models for storing data
#### Description of Task to be completed?
Have the following models created:

- User

- Article

- Comment
#### What are the relevant pivotal tracker stories?
[165663486](https://www.pivotaltracker.com/story/show/165663486)

### CODE REVIEW

**Comment by e-liyai** [comment]
@rwajon implement tests for the models created

**Comment by rwajon** [comment]
Ok, I'm gonna work on it

**Comment by e-liyai** [comment]
@rwajon migration files don't need tests. only the models

**Comment by djallas** [comment]
@e-liyai I have reviewed this PR, it contains the necessary configuration for Codeclimate and Travis-ci, what if we consider this one and close the ones raised 3 days ago, click on this [link](https://github.com/andela/ninjas-ah-backend/pull/16 and [here](https://github.com/andela/ninjas-ah-backend/pull/14)) to view them. because the CI  configurations there are not working but here there are okey.

**Pull request merged**
